#!/bin/bash

for ((i=1; i<31; i++)); do
  reply=$(curl -I -X GET http://10.40.79.190:84 | head -n 1 | awk '{print $2}')
  if [ "$reply" == "200" ];then
    echo "    200"_"$(date +%Y-%m-%d__%H.%M.%S)" >> /home/vsadmin/monitor/log.txt
  else
    echo "****   "_"$(date +%Y-%m-%d__%H.%M.%S)" >> /home/vsadmin/monitor/log.txt
  fi
sleep 2
done
